# Generated by Django 2.1.7 on 2019-03-08 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='problem_link',
            field=models.CharField(max_length=200),
        ),
    ]
