# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-09 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20190308_0613'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_ings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_no', models.BigIntegerField()),
                ('username', models.CharField(max_length=200)),
                ('problem_link', models.CharField(max_length=200)),
                ('result', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='link',
        ),
    ]
