# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-11 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_project_ings_problem_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_ings',
            name='user_link',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
