# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-11 09:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_project_ings_user_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project_ings',
            old_name='user_link',
            new_name='link_username',
        ),
    ]
